/**
 * Caddy Manager
 * 
 * Manages Caddy configuration file (Caddyfile).
 */

import * as fs from 'fs-extra';
import { writeFile, readFile } from 'fs/promises';
import * as path from 'path';
import * as os from 'os';
import { exec } from 'child_process';
import { promisify } from 'util';
import { CaddyDomainBlock, DomainInfo, DomainConfig } from './types.js';
import { CaddyfileError } from './errors.js';
import { ICaddyManager } from './interfaces.js';

const execAsync = promisify(exec);

/**
 * Caddy Manager Configuration
 */
export interface CaddyManagerConfig {
  /**
   * Caddyfile path (default: ~/.caddy/Caddyfile)
   */
  caddyfilePath?: string;
}

export class CaddyManager implements ICaddyManager {
  private caddyfilePath: string;
  private caddyfileHeader = `# Auto-generated by domain-manager
# Do not edit manually - changes will be overwritten

`;

  constructor(config?: CaddyManagerConfig) {
    if (config?.caddyfilePath) {
      this.caddyfilePath = config.caddyfilePath;
    } else {
      const homeDir = os.homedir();
      const caddyDir = path.join(homeDir, '.caddy');
      this.caddyfilePath = path.join(caddyDir, 'Caddyfile');
    }
  }

  /**
   * Read current Caddyfile
   * 
   * @returns Caddyfile content as string
   * @throws {CaddyfileError} If reading Caddyfile fails
   */
  async readCaddyfile(): Promise<string> {
    try {
      if (await fs.pathExists(this.caddyfilePath)) {
        return await readFile(this.caddyfilePath, 'utf-8');
      }
      return '';
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      throw new CaddyfileError(
        `Failed to read Caddyfile: ${errorMessage}`,
        'read',
        this.caddyfilePath
      );
    }
  }

  /**
   * Get Caddyfile directory (create if needed)
   */
  private async ensureCaddyDir(): Promise<void> {
    const caddyDir = path.dirname(this.caddyfilePath);
    if (!(await fs.pathExists(caddyDir))) {
      await fs.mkdirp(caddyDir);
    }
  }

  /**
   * Add domain block to Caddyfile
   * 
   * @param config - Domain configuration to add
   * @throws {CaddyfileError} If writing to Caddyfile fails
   */
  async addDomain(config: CaddyDomainBlock): Promise<void> {
    // Validate domain configuration
    if (!config.domain) {
      throw new CaddyfileError('Domain name is required', 'write', this.caddyfilePath);
    }

    // Validate that at least one port is provided
    if (!config.port && !config.frontendPort && !config.backendPort) {
      throw new CaddyfileError(
        'At least one port (port, frontendPort, or backendPort) must be provided',
        'write',
        this.caddyfilePath
      );
    }

    await this.ensureCaddyDir();

    let content: string;
    try {
      content = await this.readCaddyfile();
    } catch (error) {
      // If file doesn't exist, start with empty content
      if (error instanceof CaddyfileError && error.operation === 'read') {
        content = '';
      } else {
        throw error;
      }
    }

    // Remove existing entry for this domain if it exists
    content = this.removeDomainFromContent(content, config.domain);

    // Generate domain block
    const domainBlock = this.generateDomainBlock(config);

    // Append new domain block
    if (!content.trim()) {
      content = this.caddyfileHeader;
    } else if (!content.includes('# Auto-generated by domain-manager')) {
      // Add header if not present
      content = this.caddyfileHeader + content;
    }

    content += '\n' + domainBlock + '\n';

    // Write to file
    try {
      await writeFile(this.caddyfilePath, content, 'utf-8');
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      throw new CaddyfileError(
        `Failed to write Caddyfile: ${errorMessage}`,
        'write',
        this.caddyfilePath
      );
    }

    // Reload Caddy
    await this.reloadCaddy();
  }

  /**
   * Remove domain from Caddyfile
   * 
   * @param domain - Domain name to remove
   * @throws {CaddyfileError} If removing domain fails
   */
  async removeDomain(domain: string): Promise<void> {
    if (!domain || typeof domain !== 'string') {
      throw new CaddyfileError('Domain name is required', 'write', this.caddyfilePath);
    }

    let content: string;
    try {
      content = await this.readCaddyfile();
    } catch (error) {
      // If file doesn't exist, nothing to remove
      if (error instanceof CaddyfileError && error.operation === 'read') {
        return;
      }
      throw error;
    }

    const newContent = this.removeDomainFromContent(content, domain);

    if (newContent !== content) {
      try {
        await writeFile(this.caddyfilePath, newContent, 'utf-8');
      } catch (error) {
        const errorMessage = error instanceof Error ? error.message : String(error);
        throw new CaddyfileError(
          `Failed to write Caddyfile: ${errorMessage}`,
          'write',
          this.caddyfilePath
        );
      }
      await this.reloadCaddy();
    }
  }

  /**
   * List all domains in Caddyfile
   * 
   * @returns Array of domain information
   * @throws {CaddyfileError} If parsing Caddyfile fails
   */
  async listDomains(): Promise<DomainInfo[]> {
    let content: string;
    try {
      content = await this.readCaddyfile();
    } catch (error) {
      // If file doesn't exist or can't be read, return empty array
      if (error instanceof CaddyfileError && error.operation === 'read') {
        return [];
      }
      throw error;
    }

    const domains: DomainInfo[] = [];
    const lines = content.split('\n');

    let currentDomain: string | null = null;
    let currentConfig: Partial<DomainConfig> = {};
    let inDomainBlock = false;
    let lineNumber = 0;

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      lineNumber = i + 1;

      // Check for domain declaration: "domain.local {" or "http://domain.local {"
      const domainMatch = line.match(/^(?:http:\/\/)?(\S+\.local)\s*\{/);
      if (domainMatch) {
        // Save previous domain if exists
        if (currentDomain && currentConfig) {
          domains.push({
            domain: currentDomain,
            config: currentConfig as DomainConfig,
            caddyfileLine: lineNumber - 1,
          });
        }

        // Start new domain
        currentDomain = domainMatch[1];
        currentConfig = {
          domain: currentDomain,
          isMultiService: false,
        } as DomainConfig;
        inDomainBlock = true;
        continue;
      }

      // Check for closing brace
      if (inDomainBlock && line.trim() === '}') {
        if (currentDomain) {
          domains.push({
            domain: currentDomain,
            config: currentConfig as DomainConfig,
            caddyfileLine: lineNumber,
          });
        }
        currentDomain = null;
        currentConfig = {} as Partial<DomainConfig>;
        inDomainBlock = false;
        continue;
      }

      // Parse domain block content
      if (inDomainBlock && currentDomain) {
        // Check for handle /api/* block first to detect multi-service
        if (line.includes('handle /api/*')) {
          currentConfig.isMultiService = true;
          // Next line should have reverse_proxy for backend
          if (i + 1 < lines.length) {
            const nextLine = lines[i + 1];
            const apiProxyMatch = nextLine.match(/reverse_proxy\s+localhost:(\d+)/);
            if (apiProxyMatch) {
              currentConfig.backendPort = parseInt(apiProxyMatch[1]);
            }
          }
          // If we already have a port set, it's the frontend port
          if (currentConfig.port) {
            currentConfig.frontendPort = currentConfig.port;
            delete currentConfig.port;
          }
        }

        // Check for reverse_proxy
        const proxyMatch = line.match(/reverse_proxy\s+localhost:(\d+)/);
        if (proxyMatch) {
          const port = parseInt(proxyMatch[1]);
          // If it's the first proxy and not inside a handle block, it's the main port
          if (!currentConfig.port && !currentConfig.frontendPort && !currentConfig.backendPort) {
            currentConfig.port = port;
          } else if (currentConfig.isMultiService && !currentConfig.frontendPort && !line.includes('handle')) {
            // In multi-service, the first proxy outside handle is frontend
            currentConfig.frontendPort = port;
            if (currentConfig.port && !currentConfig.backendPort) {
              delete currentConfig.port;
            }
          }
        }
      }
    }

    // Add final domain if still in block (unclosed block)
    if (currentDomain && currentConfig) {
      domains.push({
        domain: currentDomain,
        config: currentConfig as DomainConfig,
        caddyfileLine: lineNumber,
      });
    }

    return domains;
  }

  /**
   * Generate Caddy domain block
   */
  private generateDomainBlock(config: CaddyDomainBlock): string {
    // Use http:// explicitly for .local domains to prevent automatic HTTPS
    // This prevents SSL certificate errors in browsers
    let block = `http://${config.domain} {\n`;

    if (config.frontendPort && config.backendPort) {
      // Multi-service: frontend + backend API
      block += `    # Frontend\n`;
      block += `    reverse_proxy localhost:${config.frontendPort}\n\n`;
      block += `    # Backend API\n`;
      block += `    handle /api/* {\n`;
      block += `        reverse_proxy localhost:${config.backendPort}\n`;
      block += `    }\n`;
    } else if (config.port) {
      // Single service
      block += `    reverse_proxy localhost:${config.port}\n`;
    } else if (config.frontendPort) {
      // Frontend only
      block += `    reverse_proxy localhost:${config.frontendPort}\n`;
    }

    block += `}`;
    return block;
  }

  /**
   * Remove domain from Caddyfile content
   */
  private removeDomainFromContent(content: string, domain: string): string {
    const lines = content.split('\n');
    const newLines: string[] = [];
    let inDomainBlock = false;
    let braceCount = 0;

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];

      // Check if this is the domain we want to remove (with or without http://)
      const domainPattern = new RegExp(`^(?:http:\\/\\/)?${domain.replace(/\./g, '\\.')}\\s*\\{`);
      if (line.match(domainPattern)) {
        inDomainBlock = true;
        braceCount = 1;
        continue; // Skip this line
      }

      if (inDomainBlock) {
        // Count braces to know when block ends
        for (const char of line) {
          if (char === '{') braceCount++;
          if (char === '}') braceCount--;
        }

        if (braceCount === 0) {
          // End of block
          inDomainBlock = false;
          continue; // Skip closing brace
        }

        // Skip all lines inside the block
        continue;
      }

      // Keep this line
      newLines.push(line);
    }

    return newLines.join('\n');
  }

  /**
   * Reload Caddy configuration
   * 
   * Attempts to reload Caddy by sending SIGHUP signal. If this fails,
   * Caddy will auto-reload on file changes or can be restarted manually.
   */
  async reloadCaddy(): Promise<void> {
    try {
      await this.sendReloadSignal();
    } catch (error) {
      // Reload failed, but that's okay - Caddy watches the file and will reload automatically
      // User can also restart Caddy manually if needed
    }
  }

  /**
   * Send SIGHUP signal to Caddy process to reload configuration
   * 
   * @private
   */
  private async sendReloadSignal(): Promise<void> {
    try {
      // Try sending SIGHUP to caddy process to reload config
      await execAsync('pkill -HUP caddy 2>/dev/null || true');
    } catch (error) {
      // If that fails, try finding caddy process and sending signal
      await this.reloadCaddyByPid();
    }
  }

  /**
   * Reload Caddy by finding process ID and sending SIGHUP
   * 
   * @private
   */
  private async reloadCaddyByPid(): Promise<void> {
    try {
      const { stdout } = await execAsync('pgrep -f caddy 2>/dev/null || true');
      if (stdout.trim()) {
        const pid = stdout.trim().split('\n')[0];
        if (pid) {
          await execAsync(`kill -HUP ${pid} 2>/dev/null || true`);
        }
      }
    } catch (error) {
      // If all fails, user will need to restart Caddy manually
      // This is not a critical error - Caddy can auto-reload on file changes
      // or user can restart manually: caddy reload --config ~/.caddy/Caddyfile
    }
  }

  /**
   * Check if Caddy is installed
   */
  async checkCaddyInstalled(): Promise<boolean> {
    try {
      await execAsync('which caddy || command -v caddy');
      return true;
    } catch (error) {
      return false;
    }
  }

  /**
   * Check if Caddy is running
   */
  async checkCaddyRunning(): Promise<boolean> {
    try {
      const { stdout } = await execAsync('pgrep -f caddy || ps aux | grep caddy | grep -v grep');
      return stdout.trim().length > 0;
    } catch (error) {
      return false;
    }
  }
}

