/**
 * Caddy Manager
 * 
 * Manages Caddy configuration file (Caddyfile).
 */

import * as fs from 'fs-extra';
import * as path from 'path';
import * as os from 'os';
import { exec } from 'child_process';
import { promisify } from 'util';
import { CaddyDomainBlock, DomainInfo } from './types';

const execAsync = promisify(exec);

export class CaddyManager {
  private caddyfilePath: string;
  private caddyfileHeader = `# Auto-generated by domain-manager
# Do not edit manually - changes will be overwritten

`;

  constructor() {
    const homeDir = os.homedir();
    const caddyDir = path.join(homeDir, '.caddy');
    this.caddyfilePath = path.join(caddyDir, 'Caddyfile');
  }

  /**
   * Read current Caddyfile
   */
  async readCaddyfile(): Promise<string> {
    try {
      if (await fs.pathExists(this.caddyfilePath)) {
        return await fs.readFile(this.caddyfilePath, 'utf-8');
      }
      return '';
    } catch (error) {
      return '';
    }
  }

  /**
   * Get Caddyfile directory (create if needed)
   */
  private async ensureCaddyDir(): Promise<void> {
    const caddyDir = path.dirname(this.caddyfilePath);
    if (!(await fs.pathExists(caddyDir))) {
      await fs.mkdirp(caddyDir);
    }
  }

  /**
   * Add domain block to Caddyfile
   */
  async addDomain(config: CaddyDomainBlock): Promise<void> {
    await this.ensureCaddyDir();

    let content = await this.readCaddyfile();

    // Remove existing entry for this domain if it exists
    content = this.removeDomainFromContent(content, config.domain);

    // Generate domain block
    const domainBlock = this.generateDomainBlock(config);

    // Append new domain block
    if (!content.trim()) {
      content = this.caddyfileHeader;
    } else if (!content.includes('# Auto-generated by domain-manager')) {
      // Add header if not present
      content = this.caddyfileHeader + content;
    }

    content += '\n' + domainBlock + '\n';

    // Write to file
    await fs.writeFile(this.caddyfilePath, content, 'utf-8');

    // Reload Caddy
    await this.reloadCaddy();
  }

  /**
   * Remove domain from Caddyfile
   */
  async removeDomain(domain: string): Promise<void> {
    const content = await this.readCaddyfile();
    const newContent = this.removeDomainFromContent(content, domain);
    
    if (newContent !== content) {
      await fs.writeFile(this.caddyfilePath, newContent, 'utf-8');
      await this.reloadCaddy();
    }
  }

  /**
   * List all domains in Caddyfile
   */
  async listDomains(): Promise<DomainInfo[]> {
    const content = await this.readCaddyfile();
    const domains: DomainInfo[] = [];
    const lines = content.split('\n');

    let currentDomain: string | null = null;
    let currentConfig: any = {};
    let inDomainBlock = false;
    let lineNumber = 0;

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      lineNumber = i + 1;

      // Check for domain declaration: "domain.local {"
      const domainMatch = line.match(/^(\S+\.local)\s*\{/);
      if (domainMatch) {
        // Save previous domain if exists
        if (currentDomain) {
          domains.push({
            domain: currentDomain,
            config: currentConfig,
            caddyfileLine: lineNumber - 1,
          });
        }

        // Start new domain
        currentDomain = domainMatch[1];
        currentConfig = {
          domain: currentDomain,
          isMultiService: false,
        };
        inDomainBlock = true;
        continue;
      }

      // Check for closing brace
      if (inDomainBlock && line.trim() === '}') {
        if (currentDomain) {
          domains.push({
            domain: currentDomain,
            config: currentConfig,
            caddyfileLine: lineNumber,
          });
        }
        currentDomain = null;
        currentConfig = {};
        inDomainBlock = false;
        continue;
      }

      // Parse domain block content
      if (inDomainBlock && currentDomain) {
        // Check for reverse_proxy
        const proxyMatch = line.match(/reverse_proxy\s+localhost:(\d+)/);
        if (proxyMatch) {
          const port = parseInt(proxyMatch[1]);
          // If it's the first proxy, it's the main port
          if (!currentConfig.port && !currentConfig.frontendPort) {
            currentConfig.port = port;
          }
        }

        // Check for handle /api/* block
        if (line.includes('handle /api/*')) {
          currentConfig.isMultiService = true;
          // Next line should have reverse_proxy
          if (i + 1 < lines.length) {
            const nextLine = lines[i + 1];
            const apiProxyMatch = nextLine.match(/reverse_proxy\s+localhost:(\d+)/);
            if (apiProxyMatch) {
              currentConfig.backendPort = parseInt(apiProxyMatch[1]);
            }
          }
        }
      }
    }

    return domains;
  }

  /**
   * Generate Caddy domain block
   */
  private generateDomainBlock(config: CaddyDomainBlock): string {
    let block = `${config.domain} {\n`;

    if (config.frontendPort && config.backendPort) {
      // Multi-service: frontend + backend API
      block += `    # Frontend\n`;
      block += `    reverse_proxy localhost:${config.frontendPort}\n\n`;
      block += `    # Backend API\n`;
      block += `    handle /api/* {\n`;
      block += `        reverse_proxy localhost:${config.backendPort}\n`;
      block += `    }\n`;
    } else if (config.port) {
      // Single service
      block += `    reverse_proxy localhost:${config.port}\n`;
    } else if (config.frontendPort) {
      // Frontend only
      block += `    reverse_proxy localhost:${config.frontendPort}\n`;
    }

    block += `}`;
    return block;
  }

  /**
   * Remove domain from Caddyfile content
   */
  private removeDomainFromContent(content: string, domain: string): string {
    const lines = content.split('\n');
    const newLines: string[] = [];
    let inDomainBlock = false;
    let braceCount = 0;

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];

      // Check if this is the domain we want to remove
      if (line.match(new RegExp(`^${domain.replace(/\./g, '\\.')}\\s*\\{`))) {
        inDomainBlock = true;
        braceCount = 1;
        continue; // Skip this line
      }

      if (inDomainBlock) {
        // Count braces to know when block ends
        for (const char of line) {
          if (char === '{') braceCount++;
          if (char === '}') braceCount--;
        }

        if (braceCount === 0) {
          // End of block
          inDomainBlock = false;
          continue; // Skip closing brace
        }

        // Skip all lines inside the block
        continue;
      }

      // Keep this line
      newLines.push(line);
    }

    return newLines.join('\n');
  }

  /**
   * Reload Caddy configuration
   */
  async reloadCaddy(): Promise<void> {
    try {
      // Try sending SIGHUP to caddy process to reload config
      try {
        await execAsync('pkill -HUP caddy 2>/dev/null || true');
      } catch (error) {
        // If that fails, try finding caddy process and sending signal
        try {
          const { stdout } = await execAsync('pgrep -f caddy 2>/dev/null || true');
          if (stdout.trim()) {
            const pid = stdout.trim().split('\n')[0];
            if (pid) {
              await execAsync(`kill -HUP ${pid} 2>/dev/null || true`);
            }
          }
        } catch (error) {
          // If all fails, user will need to restart Caddy manually
          // This is not a critical error - Caddy can auto-reload on file changes
          // or user can restart manually: caddy reload --config ~/.caddy/Caddyfile
        }
      }
    } catch (error) {
      // Reload failed, but that's okay - Caddy watches the file and will reload automatically
      // User can also restart Caddy manually if needed
    }
  }

  /**
   * Check if Caddy is installed
   */
  async checkCaddyInstalled(): Promise<boolean> {
    try {
      await execAsync('which caddy || command -v caddy');
      return true;
    } catch (error) {
      return false;
    }
  }

  /**
   * Check if Caddy is running
   */
  async checkCaddyRunning(): Promise<boolean> {
    try {
      const { stdout } = await execAsync('pgrep -f caddy || ps aux | grep caddy | grep -v grep');
      return stdout.trim().length > 0;
    } catch (error) {
      return false;
    }
  }
}

