/**
 * Caddy Manager Tests
 */

import { CaddyManager } from '../caddy-manager.js';
import { CaddyfileError } from '../errors.js';
import * as fs from 'fs-extra';
import * as path from 'path';
import * as os from 'os';
import { exec } from 'child_process';
import { promisify } from 'util';

jest.mock('fs-extra');
jest.mock('child_process');
jest.mock('util');

const execAsync = promisify(exec);

describe('CaddyManager', () => {
  let caddyManager: CaddyManager;
  let mockCaddyfilePath: string;

  beforeEach(() => {
    jest.clearAllMocks();
    caddyManager = new CaddyManager();
    mockCaddyfilePath = path.join(os.homedir(), '.caddy', 'Caddyfile');
  });

  describe('readCaddyfile', () => {
    it('should read existing Caddyfile', async () => {
      const content = 'test.local {\n    reverse_proxy localhost:3000\n}';
      (fs.pathExists as jest.Mock).mockResolvedValue(true);
      (fs.readFile as jest.Mock).mockResolvedValue(content);

      const result = await caddyManager.readCaddyfile();

      expect(result).toBe(content);
      expect(fs.readFile).toHaveBeenCalledWith(mockCaddyfilePath, 'utf-8');
    });

    it('should return empty string if file does not exist', async () => {
      (fs.pathExists as jest.Mock).mockResolvedValue(false);

      const result = await caddyManager.readCaddyfile();

      expect(result).toBe('');
      expect(fs.readFile).not.toHaveBeenCalled();
    });

    it('should throw CaddyfileError if read fails', async () => {
      (fs.pathExists as jest.Mock).mockResolvedValue(true);
      (fs.readFile as jest.Mock).mockRejectedValue(new Error('Read failed'));

      await expect(caddyManager.readCaddyfile()).rejects.toThrow(
        CaddyfileError
      );
    });
  });

  describe('addDomain', () => {
    beforeEach(() => {
      (fs.pathExists as jest.Mock).mockResolvedValue(false);
      (fs.mkdirp as jest.Mock).mockResolvedValue(undefined);
      (fs.writeFile as jest.Mock).mockResolvedValue(undefined);
      (execAsync as jest.Mock).mockResolvedValue({ stdout: '', stderr: '' });
    });

    it('should validate domain name', async () => {
      await expect(
        caddyManager.addDomain({
          domain: '',
          port: 3000,
        } as any)
      ).rejects.toThrow(CaddyfileError);
    });

    it('should validate that at least one port is provided', async () => {
      await expect(
        caddyManager.addDomain({
          domain: 'test.local',
        } as any)
      ).rejects.toThrow(CaddyfileError);
    });

    it('should add single-service domain block', async () => {
      (fs.pathExists as jest.Mock).mockResolvedValue(false);

      await caddyManager.addDomain({
        domain: 'test.local',
        port: 3000,
      });

      expect(fs.writeFile).toHaveBeenCalled();
      const writtenContent = (fs.writeFile as jest.Mock).mock.calls[0][1];
      expect(writtenContent).toContain('test.local {');
      expect(writtenContent).toContain('reverse_proxy localhost:3000');
    });

    it('should add multi-service domain block', async () => {
      (fs.pathExists as jest.Mock).mockResolvedValue(false);

      await caddyManager.addDomain({
        domain: 'test.local',
        frontendPort: 4200,
        backendPort: 8080,
      });

      const writtenContent = (fs.writeFile as jest.Mock).mock.calls[0][1];
      expect(writtenContent).toContain('test.local {');
      expect(writtenContent).toContain('reverse_proxy localhost:4200');
      expect(writtenContent).toContain('handle /api/*');
      expect(writtenContent).toContain('reverse_proxy localhost:8080');
    });

    it('should remove existing domain before adding', async () => {
      const existingContent = 'old.local {\n    reverse_proxy localhost:3000\n}';
      (fs.pathExists as jest.Mock).mockResolvedValue(true);
      (fs.readFile as jest.Mock).mockResolvedValue(existingContent);

      await caddyManager.addDomain({
        domain: 'test.local',
        port: 3000,
      });

      const writtenContent = (fs.writeFile as jest.Mock).mock.calls[0][1];
      expect(writtenContent).toContain('test.local');
      expect(writtenContent).not.toContain('old.local');
    });

    it('should add header to new file', async () => {
      (fs.pathExists as jest.Mock).mockResolvedValue(false);

      await caddyManager.addDomain({
        domain: 'test.local',
        port: 3000,
      });

      const writtenContent = (fs.writeFile as jest.Mock).mock.calls[0][1];
      expect(writtenContent).toContain('# Auto-generated by domain-manager');
    });

    it('should throw CaddyfileError if write fails', async () => {
      (fs.pathExists as jest.Mock).mockResolvedValue(false);
      (fs.writeFile as jest.Mock).mockRejectedValue(
        new Error('Write failed')
      );

      await expect(
        caddyManager.addDomain({
          domain: 'test.local',
          port: 3000,
        })
      ).rejects.toThrow(CaddyfileError);
    });
  });

  describe('removeDomain', () => {
    it('should validate domain name', async () => {
      await expect(caddyManager.removeDomain('')).rejects.toThrow(
        CaddyfileError
      );
    });

    it('should remove domain from Caddyfile', async () => {
      const content = `test.local {
    reverse_proxy localhost:3000
}`;
      (fs.pathExists as jest.Mock).mockResolvedValue(true);
      (fs.readFile as jest.Mock).mockResolvedValue(content);
      (fs.writeFile as jest.Mock).mockResolvedValue(undefined);
      (execAsync as jest.Mock).mockResolvedValue({ stdout: '', stderr: '' });

      await caddyManager.removeDomain('test.local');

      expect(fs.writeFile).toHaveBeenCalled();
      const writtenContent = (fs.writeFile as jest.Mock).mock.calls[0][1];
      expect(writtenContent).not.toContain('test.local');
    });

    it('should return early if file does not exist', async () => {
      (fs.pathExists as jest.Mock).mockResolvedValue(true);
      (fs.readFile as jest.Mock).mockRejectedValue(
        new CaddyfileError('File not found', 'read', mockCaddyfilePath)
      );

      await caddyManager.removeDomain('test.local');

      expect(fs.writeFile).not.toHaveBeenCalled();
    });

    it('should throw CaddyfileError if write fails', async () => {
      const content = 'test.local {\n    reverse_proxy localhost:3000\n}';
      (fs.pathExists as jest.Mock).mockResolvedValue(true);
      (fs.readFile as jest.Mock).mockResolvedValue(content);
      (fs.writeFile as jest.Mock).mockRejectedValue(
        new Error('Write failed')
      );

      await expect(caddyManager.removeDomain('test.local')).rejects.toThrow(
        CaddyfileError
      );
    });
  });

  describe('listDomains', () => {
    it('should parse single-service domain', async () => {
      const content = `test.local {
    reverse_proxy localhost:3000
}`;
      (fs.pathExists as jest.Mock).mockResolvedValue(true);
      (fs.readFile as jest.Mock).mockResolvedValue(content);

      const result = await caddyManager.listDomains();

      expect(result).toHaveLength(1);
      expect(result[0].domain).toBe('test.local');
      expect(result[0].config.port).toBe(3000);
      expect(result[0].config.isMultiService).toBe(false);
    });

    it('should parse multi-service domain', async () => {
      const content = `test.local {
    reverse_proxy localhost:4200

    handle /api/* {
        reverse_proxy localhost:8080
    }
}`;
      (fs.pathExists as jest.Mock).mockResolvedValue(true);
      (fs.readFile as jest.Mock).mockResolvedValue(content);

      const result = await caddyManager.listDomains();

      expect(result).toHaveLength(1);
      expect(result[0].domain).toBe('test.local');
      expect(result[0].config.isMultiService).toBe(true);
      expect(result[0].config.frontendPort).toBe(4200);
      expect(result[0].config.backendPort).toBe(8080);
    });

    it('should return empty array if file does not exist', async () => {
      (fs.pathExists as jest.Mock).mockResolvedValue(true);
      (fs.readFile as jest.Mock).mockRejectedValue(
        new CaddyfileError('File not found', 'read', mockCaddyfilePath)
      );

      const result = await caddyManager.listDomains();

      expect(result).toEqual([]);
    });

    it('should handle multiple domains', async () => {
      const content = `test1.local {
    reverse_proxy localhost:3000
}

test2.local {
    reverse_proxy localhost:4000
}`;
      (fs.pathExists as jest.Mock).mockResolvedValue(true);
      (fs.readFile as jest.Mock).mockResolvedValue(content);

      const result = await caddyManager.listDomains();

      expect(result).toHaveLength(2);
      expect(result[0].domain).toBe('test1.local');
      expect(result[1].domain).toBe('test2.local');
    });
  });

  describe('checkCaddyInstalled', () => {
    it('should return true if Caddy is installed', async () => {
      (execAsync as jest.Mock).mockResolvedValue({ stdout: '', stderr: '' });

      const result = await caddyManager.checkCaddyInstalled();

      expect(result).toBe(true);
    });

    it('should return false if Caddy is not installed', async () => {
      (execAsync as jest.Mock).mockRejectedValue(new Error('Command failed'));

      const result = await caddyManager.checkCaddyInstalled();

      expect(result).toBe(false);
    });
  });

  describe('checkCaddyRunning', () => {
    it('should return true if Caddy is running', async () => {
      (execAsync as jest.Mock).mockResolvedValue({
        stdout: '12345',
        stderr: '',
      });

      const result = await caddyManager.checkCaddyRunning();

      expect(result).toBe(true);
    });

    it('should return false if Caddy is not running', async () => {
      (execAsync as jest.Mock).mockResolvedValue({ stdout: '', stderr: '' });

      const result = await caddyManager.checkCaddyRunning();

      expect(result).toBe(false);
    });
  });
});
