/**
 * Git Hook Generator
 * 
 * Generates post-checkout git hook with project-specific colors
 */

import * as path from 'path';
import * as fs from 'fs-extra';
import { execSync } from 'child_process';
import { ProjectColorPalette } from './color-manager';

/**
 * Generate post-checkout hook with project colors
 */
export async function generatePostCheckoutHook(
  projectPath: string,
  palette: ProjectColorPalette
): Promise<void> {
  const hookPath = path.join(projectPath, '.githooks', 'post-checkout');
  
  // Ensure .githooks directory exists
  await fs.ensureDir(path.dirname(hookPath));
  
  const hookContent = generateHookScript(palette);
  
  await fs.writeFile(hookPath, hookContent, { mode: 0o755 });
}

/**
 * Generate the hook script content
 */
function generateHookScript(palette: ProjectColorPalette): string {
  return `#!/usr/bin/env bash

### THIS IS A GIT HOOK THAT SETS THE COLOR SCHEME BASED ON THE BRANCH ###
### Generated by @your-org/core init command ###
### Colors are unique per project and built around KEY_COLOR ###

set -e

BRANCH="$(git rev-parse --abbrev-ref HEAD)"
SETTINGS_FILE=".vscode/settings.json"

# KEY_COLOR - Unique color for this project (70's inspired palette)
KEY_COLOR="${palette.keyColor}"

# Main branch colors (red-based for distinction)
MAIN_COLOR="${palette.mainColor}"
MAIN_BG="${palette.mainBg}"
MAIN_INACTIVE="${palette.mainInactive}"

# Development branch colors (orange-based)
DEV_COLOR="${palette.devColor}"
DEV_BG="${palette.devBg}"
DEV_INACTIVE="${palette.devInactive}"

# Project colors (built around KEY_COLOR)
PROJECT_COLOR="${palette.projectColor}"
PROJECT_INACTIVE="${palette.projectInactive}"
PROJECT_BG="${palette.projectBg}"

# Border and background colors (derived from KEY_COLOR)
BORDER="${palette.border}"
DARKER_BG="${palette.darkerBg}"
DARK_BG="${palette.darkBg}"
ACTIVE_COLOR="${palette.activeColor}"

echo "BRANCH: $BRANCH"
echo "Current branch is: $BRANCH"
echo "KEY_COLOR: $KEY_COLOR"

mkdir -p .vscode

if [ "$BRANCH" = "main" ] || [ "$BRANCH" = "master" ]; then
  # Main branch - RED
  COLOR="$MAIN_COLOR"
  INACTIVE="$MAIN_INACTIVE"
  BG="$MAIN_BG"
elif [ "$BRANCH" = "development" ] || [ "$BRANCH" = "dev" ]; then
  # Development branch - ORANGE
  COLOR="$DEV_COLOR"
  INACTIVE="$DEV_INACTIVE"
  BG="$DEV_BG"
else
  # Other branches - Project KEY_COLOR
  COLOR="$PROJECT_COLOR"
  INACTIVE="$PROJECT_INACTIVE"
  BG="$PROJECT_BG"
fi

# Determine branch-specific colors for UI elements
if [ "$BRANCH" = "main" ] || [ "$BRANCH" = "master" ]; then
  STATUS_BG="$MAIN_BG"
  STATUS_COLOR="$MAIN_COLOR"
  ACTIVITY_FG="$MAIN_BG"
  FOCUS_BORDER="$MAIN_BG"
  TAB_BORDER="$MAIN_BG"
elif [ "$BRANCH" = "development" ] || [ "$BRANCH" = "dev" ]; then
  STATUS_BG="$DEV_BG"
  STATUS_COLOR="$DEV_COLOR"
  ACTIVITY_FG="$DEV_BG"
  FOCUS_BORDER="$DEV_BG"
  TAB_BORDER="$DEV_BG"
else
  STATUS_BG="$PROJECT_BG"
  STATUS_COLOR="$PROJECT_COLOR"
  ACTIVITY_FG="$PROJECT_BG"
  FOCUS_BORDER="$PROJECT_BG"
  TAB_BORDER="$PROJECT_BG"
fi

cat > "$SETTINGS_FILE" <<EOF
{
    "workbench.colorCustomizations": {
      /* Title bar */
      "titleBar.activeBackground": "$BG",
      "titleBar.activeForeground": "$COLOR",
      "titleBar.inactiveBackground": "$INACTIVE",
      "titleBar.inactiveForeground": "$COLOR",
  
      /* Status bar */
      "statusBar.background": "$STATUS_BG",
      "statusBar.foreground": "$STATUS_COLOR",
      "statusBar.border": "$BORDER",
  
      /* Activity bar */
      "activityBar.background": "$DARKER_BG",
      "activityBar.foreground": "$ACTIVITY_FG",
      "activityBar.activeBorder": "$ACTIVITY_FG",
  
      /* Sidebar */
      "sideBar.background": "$DARK_BG",
      "sideBar.border": "$BORDER",
  
      /* Editor & panels frame */
      "editorGroup.border": "$BORDER",
      "panel.border": "$BORDER",
  
      /* Focus & highlights */
      "focusBorder": "$FOCUS_BORDER",
  
      /* Tabs */
      "tab.activeBorderTop": "$TAB_BORDER",
      "tab.activeForeground": "$ACTIVE_COLOR"
    }
  }
  
EOF
`;
}

/**
 * Setup git hooks path configuration
 */
export async function setupGitHooksPath(projectPath: string): Promise<void> {
  try {
    // Check if git is initialized
    const gitDir = path.join(projectPath, '.git');
    if (!(await fs.pathExists(gitDir))) {
      // Git not initialized - that's okay, skip
      return;
    }
    
    // Set git hooks path to .githooks
    execSync('git config core.hooksPath .githooks', { cwd: projectPath, stdio: 'inherit' });
  } catch (error) {
    // Git not initialized or not a git repo - that's okay, skip
    // The hook will be created but won't work until git is initialized
  }
}

/**
 * Ensure .vscode/settings.json is in .gitignore
 */
export async function ensureSettingsIgnored(projectPath: string): Promise<void> {
  const gitignorePath = path.join(projectPath, '.gitignore');
  const ignoreEntry = '.vscode/settings.json';
  
  let gitignoreContent = '';
  if (await fs.pathExists(gitignorePath)) {
    gitignoreContent = await fs.readFile(gitignorePath, 'utf-8');
  }
  
  // Check if already ignored
  if (!gitignoreContent.includes(ignoreEntry)) {
    // Add to gitignore if not already there
    const newContent = gitignoreContent
      ? `${gitignoreContent}\n${ignoreEntry}\n`
      : `${ignoreEntry}\n`;
    
    await fs.writeFile(gitignorePath, newContent);
  }
}
