/**
 * Git Hook Generator
 * 
 * Generates post-checkout git hook with project-specific colors
 */

import * as path from 'path';
import fs from 'fs-extra';
import { readFile } from 'fs/promises';
import { execSync } from 'child_process';
import { ProjectColorPalette } from './color-manager.js';

/**
 * Generate post-checkout hook with project colors
 */
export async function generatePostCheckoutHook(
  projectPath: string,
  palette: ProjectColorPalette
): Promise<void> {
  const hookPath = path.join(projectPath, '.githooks', 'post-checkout');
  
  // Ensure .githooks directory exists
  await fs.ensureDir(path.dirname(hookPath));
  
  const hookContent = generateHookScript(palette);
  
  await fs.writeFile(hookPath, hookContent, { mode: 0o755 });
}

/**
 * Generate the hook script content
 */
function generateHookScript(palette: ProjectColorPalette): string {
  return `#!/usr/bin/env bash

### THIS IS A GIT HOOK THAT SETS THE COLOR SCHEME BASED ON THE BRANCH ###
### Generated by @colis/rig init command ###
### Colors are unique per project and built around KEY_COLOR ###

set -e

BRANCH="$(git rev-parse --abbrev-ref HEAD)"
SETTINGS_FILE=".vscode/settings.json"

# KEY_COLOR - Unique color for this project (assigned only during init)
KEY_COLOR="${palette.keyColor}"

# Main branch colors (red-based for distinction)
MAIN_COLOR="${palette.mainColor}"
MAIN_BG="${palette.mainBg}"
MAIN_INACTIVE="${palette.mainInactive}"

# Development branch colors (orange-based)
DEV_COLOR="${palette.devColor}"
DEV_BG="${palette.devBg}"
DEV_INACTIVE="${palette.devInactive}"

# Project colors (built around KEY_COLOR)
PROJECT_COLOR="${palette.projectColor}"
PROJECT_INACTIVE="${palette.projectInactive}"
PROJECT_BG="${palette.projectBg}"

# Border and background colors (derived from KEY_COLOR)
BORDER="${palette.border}"
DARKER_BG="${palette.darkerBg}"
DARK_BG="${palette.darkBg}"
ACTIVE_COLOR="${palette.activeColor}"

echo "BRANCH: $BRANCH"
echo "Current branch is: $BRANCH"
echo "KEY_COLOR: $KEY_COLOR"

mkdir -p .vscode

if [ "$BRANCH" = "main" ] || [ "$BRANCH" = "master" ]; then
  # Main branch - RED
  COLOR="$MAIN_COLOR"
  INACTIVE="$MAIN_INACTIVE"
  BG="$MAIN_BG"
elif [ "$BRANCH" = "development" ] || [ "$BRANCH" = "dev" ]; then
  # Development branch - ORANGE
  COLOR="$DEV_COLOR"
  INACTIVE="$DEV_INACTIVE"
  BG="$DEV_BG"
else
  # Other branches - Project KEY_COLOR
  COLOR="$PROJECT_COLOR"
  INACTIVE="$PROJECT_INACTIVE"
  BG="$PROJECT_BG"
fi

# Determine branch-specific colors for UI elements
if [ "$BRANCH" = "main" ] || [ "$BRANCH" = "master" ]; then
  STATUS_BG="$MAIN_BG"
  STATUS_COLOR="$MAIN_COLOR"
  ACTIVITY_FG="$MAIN_BG"
  FOCUS_BORDER="$MAIN_BG"
  TAB_BORDER="$MAIN_BG"
elif [ "$BRANCH" = "development" ] || [ "$BRANCH" = "dev" ]; then
  STATUS_BG="$DEV_BG"
  STATUS_COLOR="$DEV_COLOR"
  ACTIVITY_FG="$DEV_BG"
  FOCUS_BORDER="$DEV_BG"
  TAB_BORDER="$DEV_BG"
else
  STATUS_BG="$PROJECT_BG"
  STATUS_COLOR="$PROJECT_COLOR"
  ACTIVITY_FG="$PROJECT_BG"
  FOCUS_BORDER="$PROJECT_BG"
  TAB_BORDER="$PROJECT_BG"
fi

cat > "$SETTINGS_FILE" <<EOF
{
    "workbench.colorCustomizations": {
      /* Title bar */
      "titleBar.activeBackground": "$BG",
      "titleBar.activeForeground": "$COLOR",
      "titleBar.inactiveBackground": "$INACTIVE",
      "titleBar.inactiveForeground": "$COLOR",
  
      /* Status bar */
      "statusBar.background": "$STATUS_BG",
      "statusBar.foreground": "$STATUS_COLOR",
      "statusBar.border": "$BORDER",
  
      /* Activity bar */
      "activityBar.background": "$DARKER_BG",
      "activityBar.foreground": "$ACTIVITY_FG",
      "activityBar.activeBorder": "$ACTIVITY_FG",
  
      /* Sidebar */
      "sideBar.background": "$DARK_BG",
      "sideBar.border": "$BORDER",
  
      /* Editor & panels frame */
      "editorGroup.border": "$BORDER",
      "panel.border": "$BORDER",
  
      /* Focus & highlights */
      "focusBorder": "$FOCUS_BORDER",
  
      /* Tabs */
      "tab.activeBorderTop": "$TAB_BORDER",
      "tab.activeForeground": "$ACTIVE_COLOR"
    }
  }
  
EOF
`;
}

/**
 * Setup git hooks path configuration
 */
export async function setupGitHooksPath(projectPath: string): Promise<void> {
  try {
    // Check if git is initialized
    const gitDir = path.join(projectPath, '.git');
    if (!(await fs.pathExists(gitDir))) {
      // Git not initialized - that's okay, skip
      return;
    }
    
    // Set git hooks path to .githooks
    execSync('git config core.hooksPath .githooks', { cwd: projectPath, stdio: 'inherit' });
  } catch (error) {
    // Git not initialized or not a git repo - that's okay, skip
    // The hook will be created but won't work until git is initialized
  }
}

/**
 * Initialize settings.json with colors (for when git is not available)
 */
export async function initializeSettingsJson(
  projectPath: string,
  palette: ProjectColorPalette,
  branchName: string = 'main'
): Promise<void> {
  const settingsPath = path.join(projectPath, '.vscode', 'settings.json');
  await fs.ensureDir(path.dirname(settingsPath));
  
  // Determine colors based on branch
  
  // Determine colors based on branch
  let color: string;
  let inactive: string;
  let bg: string;
  let statusBg: string;
  let statusColor: string;
  let activityFg: string;
  let focusBorder: string;
  let tabBorder: string;
  
  if (branchName === 'main' || branchName === 'master') {
    color = palette.mainColor;
    inactive = palette.mainInactive;
    bg = palette.mainBg;
    statusBg = palette.mainBg;
    statusColor = palette.mainColor;
    activityFg = palette.mainBg;
    focusBorder = palette.mainBg;
    tabBorder = palette.mainBg;
  } else if (branchName === 'development' || branchName === 'dev') {
    color = palette.devColor;
    inactive = palette.devInactive;
    bg = palette.devBg;
    statusBg = palette.devBg;
    statusColor = palette.devColor;
    activityFg = palette.devBg;
    focusBorder = palette.devBg;
    tabBorder = palette.devBg;
  } else {
    color = palette.projectColor;
    inactive = palette.projectInactive;
    bg = palette.projectBg;
    statusBg = palette.projectBg;
    statusColor = palette.projectColor;
    activityFg = palette.projectBg;
    focusBorder = palette.projectBg;
    tabBorder = palette.projectBg;
  }
  
  const settingsContent = {
    'workbench.colorCustomizations': {
      'titleBar.activeBackground': bg,
      'titleBar.activeForeground': color,
      'titleBar.inactiveBackground': inactive,
      'titleBar.inactiveForeground': color,
      'statusBar.background': statusBg,
      'statusBar.foreground': statusColor,
      'statusBar.border': palette.border,
      'activityBar.background': palette.darkerBg,
      'activityBar.foreground': activityFg,
      'activityBar.activeBorder': activityFg,
      'sideBar.background': palette.darkBg,
      'sideBar.border': palette.border,
      'editorGroup.border': palette.border,
      'panel.border': palette.border,
      'focusBorder': focusBorder,
      'tab.activeBorderTop': tabBorder,
      'tab.activeForeground': palette.activeColor,
    },
  };
  
  await fs.writeFile(settingsPath, JSON.stringify(settingsContent, null, 2) + '\n');
}

/**
 * Ensure .vscode/settings.json is in .gitignore and remove from git tracking
 */
export async function ensureSettingsIgnored(projectPath: string): Promise<void> {
  const gitignorePath = path.join(projectPath, '.gitignore');
  const ignoreEntry = '.vscode/settings.json';
  
  // Add to .gitignore if not already there
  let gitignoreContent = '';
  if (await fs.pathExists(gitignorePath)) {
    gitignoreContent = await readFile(gitignorePath, 'utf-8');
  }
  
  // Check if already ignored
  if (!gitignoreContent.includes(ignoreEntry)) {
    // Add to gitignore if not already there
    const newContent = gitignoreContent
      ? `${gitignoreContent}\n${ignoreEntry}\n`
      : `${ignoreEntry}\n`;
    
    await fs.writeFile(gitignorePath, newContent);
  }
  
  // Remove from git tracking if it's currently tracked
  try {
    const gitDir = path.join(projectPath, '.git');
    if (await fs.pathExists(gitDir)) {
      // Check if file is tracked by git
      try {
        execSync(`git ls-files --error-unmatch "${ignoreEntry}"`, {
          cwd: projectPath,
          stdio: 'pipe',
        });
        // File is tracked, remove it from git
        execSync(`git rm --cached "${ignoreEntry}"`, {
          cwd: projectPath,
          stdio: 'pipe',
        });
      } catch (error: any) {
        // File is not tracked or doesn't exist - that's fine
        // The error code will be non-zero if file is not tracked
      }
    }
  } catch (error) {
    // Git not initialized or command failed - that's okay
    // The file will still be ignored via .gitignore
  }
}
